// package com.githubyss.mobile.common.kit.regex
//
// object ComkitRegExConstantsTest {
//     object MathematicalNumber {
//         val POSITIVE_INTEGER_ZERO_CONVENTIONAL = "0"
//         val POSITIVE_INTEGER_ZERO_BEGIN_WITH_ONE_ZERO = "00"
//         val POSITIVE_INTEGER_ZERO_BEGIN_WITH_MULTIPLE_ZERO = "0000"
//
//         val NEGATIVE_INTEGER_ZERO_CONVENTIONAL = "-0"
//         val NEGATIVE_INTEGER_ZERO_BEGIN_WITH_ONE_ZERO = "-00"
//         val NEGATIVE_INTEGER_ZERO_BEGIN_WITH_MULTIPLE_ZERO = "-0000"
//
//         val POSITIVE_INTEGER_CONVENTIONAL = "1234"
//         val POSITIVE_INTEGER_BEGIN_WITH_ONE_ZERO = "01234"
//         val POSITIVE_INTEGER_BEGIN_WITH_MULTIPLE_ZERO = "0001234"
//
//         val NEGATIVE_INTEGER_CONVENTIONAL = "-1234"
//         val NEGATIVE_INTEGER_BEGIN_WITH_ONE_ZERO = "-01234"
//         val NEGATIVE_INTEGER_BEGIN_WITH_MULTIPLE_ZERO = "-0001234"
//
//
//         val POSITIVE_FLOAT_ONE_DECIMAL_ZERO_CONVENTIONAL = "0.0"
//         val POSITIVE_FLOAT_ONE_DECIMAL_ZERO_BEGIN_WITH_ONE_ZERO = "00.0"
//         val POSITIVE_FLOAT_ONE_DECIMAL_ZERO_BEGIN_WITH_MULTIPLE_ZERO = "0000.0"
//
//         val NEGATIVE_FLOAT_ONE_DECIMAL_ZERO_CONVENTIONAL = "-0.0"
//         val NEGATIVE_FLOAT_ONE_DECIMAL_ZERO_BEGIN_WITH_ONE_ZERO = "-00.0"
//         val NEGATIVE_FLOAT_ONE_DECIMAL_ZERO_BEGIN_WITH_MULTIPLE_ZERO = "-0000.0"
//
//         val POSITIVE_FLOAT_ONE_DECIMAL_CONVENTIONAL = "1234.0"
//         val POSITIVE_FLOAT_ONE_DECIMAL_BEGIN_WITH_ONE_ZERO = "01234.0"
//         val POSITIVE_FLOAT_ONE_DECIMAL_BEGIN_WITH_MULTIPLE_ZERO = "0001234.0"
//
//         val NEGATIVE_FLOAT_ONE_DECIMAL_CONVENTIONAL = "-1234.0"
//         val NEGATIVE_FLOAT_ONE_DECIMAL_BEGIN_WITH_ONE_ZERO = "-01234.0"
//         val NEGATIVE_FLOAT_ONE_DECIMAL_BEGIN_WITH_MULTIPLE_ZERO = "-0001234.0"
//     }
// }
